#!/usr/bin/env python3
"""Regenerate registry/comet-curies.json — the canonical set of CURIEs that
CarbonSig repos are allowed to reference.

Sources:
  1. COMET's published terms (docs/ontology-data.json from Carbonsig/comet-ontology)
  2. The comet-pcr extension TTL in this repo (pending-upstream terms)

The result is a flat, sorted, language-neutral allow-list. Both verifier-export
(TS) and pcrbase (Python) validate every COMET CURIE they reference against it.

Usage:
  python tools/build_registry.py --comet-data /path/to/comet-ontology/docs/ontology-data.json
  python tools/build_registry.py            # auto-discovers a sibling comet-ontology checkout
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NS_FILE = ROOT / "registry" / "namespaces.json"
PCR_TTL = ROOT / "extensions" / "comet-pcr.ttl"
OUT = ROOT / "registry" / "comet-curies.json"

# Term-defining predicates in the extension TTL (subject is a defined term).
_DEF_RE = re.compile(
    r"^(comet-pcr:[A-Za-z0-9_]+)\s+a\s+(owl:Class|owl:ObjectProperty|owl:DatatypeProperty|skos:Concept|skos:ConceptScheme)",
    re.MULTILINE,
)


def load_namespaces() -> dict:
    return json.loads(NS_FILE.read_text())


def comet_curies(comet_data: Path) -> list[str]:
    data = json.loads(comet_data.read_text())
    # Only COMET-owned terms (skip incorporated CAD Trust dictionary rows).
    comet_prefixes = {"comet", "comet-ef", "comet-sc", "comet-pcf", "comet-eac",
                      "comet-ver", "comet-mkt", "comet-rs", "comet-cn"}
    return sorted({t["curie"] for t in data["terms"] if t.get("prefix") in comet_prefixes})


def pcr_curies() -> list[str]:
    text = PCR_TTL.read_text()
    return sorted({m.group(1) for m in _DEF_RE.finditer(text)})


def discover_comet_data() -> Path | None:
    for cand in [
        ROOT.parent / "comet-ontology" / "docs" / "ontology-data.json",
        ROOT / "vendor" / "comet-ontology" / "docs" / "ontology-data.json",
    ]:
        if cand.exists():
            return cand
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--comet-data", type=Path, default=None,
                    help="Path to comet-ontology docs/ontology-data.json")
    args = ap.parse_args()

    comet_data = args.comet_data or discover_comet_data()
    if not comet_data or not comet_data.exists():
        print("ERROR: could not find comet-ontology ontology-data.json; pass --comet-data PATH")
        return 1

    ns = load_namespaces()
    core = comet_curies(comet_data)
    pending = pcr_curies()

    registry = {
        "description": "Allow-list of COMET CURIEs that CarbonSig repos may reference. "
                       "Generated by tools/build_registry.py — do not hand-edit.",
        "comet_source": str(comet_data.name),
        "namespaces": {**ns["comet_core"], **ns["comet_extensions"], **ns["carbonsig"]},
        "counts": {"comet_published": len(core), "comet_pcr_pending": len(pending),
                   "total": len(core) + len(pending)},
        "comet_published": core,
        "comet_pcr_pending": pending,
    }
    OUT.write_text(json.dumps(registry, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: "
          f"{len(core)} published + {len(pending)} pending comet-pcr = {len(core)+len(pending)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
